CREATE TABLE Processes(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    TIMEFROM TEXT NOT NULL,
    TIMETO TEXT NOT NULL,
    CATEGORY TEXT
);

CREATE TABLE DURATIONS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    LASTUPDATED TEXT NOT NULL,
    DURATION INTEGER NOT NULL
);