[package]
name = "tracker"
version = "0.1.0"
authors = ["mysjkin <iarogolo@gmail.com>"]
edition = "2018"
build  = "build.rs"

[dependencies]
libxdo-sys = "0.11.0"
libc = "0.2.20"
rusqlite = "0.17.0"
chrono = "0.4.6"
sysinfo = "0.8.2"
azul = { git = "https://github.com/maps4print/azul" }